version: '3.8'

services:
  users_database:
    image: postgres:16.3-bullseye
    container_name: users_database
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "15432:5432"
    volumes:
      - ./pgsql/data:/var/lib/postgresql/data